### PR TITLE
Determine if weeks should start on mondays by locale

### PR DESCRIPTION
**Pull request by Tyilo**
This only changes the default value.
I have also added the --sunday option to force
showing weeks starting with Sunday.

### CODE REVIEW

**Comment by jcrowgey** [comment]
Can you refactor to use the `locale` module?

https://docs.python.org/3.5/library/locale.html

We already pull in this module (see here https://github.com/insanum/gcalcli/blob/6cf4bf54ca5aa8b9778b8d80fccfb074b09798c5/gcalcli/utils.py#L3).

**Comment by Tyilo** [comment]
No, this doesn't seem possible.

**Comment by jcrowgey** [comment]
I wonder why you say that.

```shell
$ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.nl_langinfo(locale.ABDAY_1)
'Sun'
```

**Comment by Tyilo** [comment]
No, this doesn't work.

On my system I also get `Sun`:
```
$ ipython
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import locale                                                                                                                                                                                                

In [2]: locale.nl_langinfo(locale.ABDAY_1)                                                                                                                                                                           
Out[2]: 'Sun'
```

Even though:
```
$ locale first_weekday
2
```

I think this because `ABDAY_1` just gives you the abbreviated name of day 1 (which is always Sunday), which might be different in another language.

**Comment by jcrowgey** [comment]
Hmm, yes I see as well that we're not the first to stumble across this: https://blogs.gnome.org/patrys/2008/09/29/how-to-determine-the-first-day-of-week/

**Comment by Tyilo** [comment]
I updated the code to use the logic described in that blog post.

**Comment by jcrowgey** [comment]
I've merged the other PR, please rebase this one.  To be honest and upfront, I'm going to sit on this one for a minute and think about a few issues.  Thank you very much for this work.  Even if this isn't merged eventually, it has still been very educational for me.

**Comment by Tyilo** [comment]
Rebased.

**Pull request closed without merging**
