### PR TITLE
argparsers: add url to BOOL_DETAILS [fixes #435]

### LINKED ISSUE #435: --details is broken for --tsv
--details all: does not work (not all details are visible e.g. longurl and other details)

if --details all is active all other --details parameters are ignored like --details longurl

### PR DESCRIPTION
**Pull request by jcrowgey**

### CODE REVIEW

**Comment by jcrowgey** [comment]
Ok, thanks Travis ;)

@lasers, I'd like to implement this in a way that respects the default shorturl (and which allows overriding it)

If you want the commit history here, please implement something along the lines of https://github.com/insanum/gcalcli:fix_details_all_url

**Comment by lasers** [comment]
Implemented your code, tested OK with `url, longurl, shorturl` and pushed. On side note, it sucks a bit to allow only one `--details` choice. Not complaining though.

**Comment by lasers** [comment]
Close #435. I take it if one opens a PR from anywhere, one gets all the credits. Still your code. :+1:

**Comment by jcrowgey** [comment]
Ha, thanks Lasers.  I never know whether people value getting their commits into a project or not.  In any case, I have plenty of commits in gcalcli and I'm happy to share.  :)

Thanks for the work on this.

**Pull request merged**
