### PR TITLE
Implement show-end-time argument #430

### PR DESCRIPTION
**Pull request by mortezaipo**

### CODE REVIEW

**Comment by jcrowgey** [comment]
Hi!  Thanks for taking this one on!

Two things:
1)  Can you add some testing to help ensure your new functionality doesn't get broken in the future?
2) Can you talk about why we shouldn't have this as part of the --details parsing?

**Comment by mortezaipo** [comment]
> Hi! Thanks for taking this one on!
> 
> Two things:
> 
> 1. Can you add some testing to help ensure your new functionality doesn't get broken in the future?
> 2. Can you talk about why we shouldn't have this as part of the --details parsing?

Hi,

About adding tests, I'll add some tests.
About `--details` I completely agree to port this argument in this category but does `--details` talk about event's payload or it can be about the event's metadata (e.g. from, to, ...)?

**Comment by jcrowgey** [comment]
> About --details I completely agree to port this argument in this category but does --details talk about event's payload or it can be about the event's metadata (e.g. from, to, ...)?

The values passed to ```--details``` are supposed to say what information about the events are printed in the output.  By default we print the event title and start time, saying ```--details url``` should also print a url for the event (if present), saying ```--details all``` should print everything that we know how to print.  So I think that ```---details stoptime``` (or maybe "endtime", try to follow what the google calendar api uses) would be the way to add stoptime printing.   I'm not 100% sure if that answers your question, feel free to follow up if you need something clarified.

**Comment by mortezaipo** [comment]
Hi,
I've updated my pull request. Would you please review it.

**Comment by mortezaipo** [comment]
Done ;)

**Comment by jcrowgey** [comment]
> Done ;)

You're still only messing with the 12-hour branch of the code though.

I push a commit to your branch (thanks for allowing that).  How does that look to you?

**Comment by mortezaipo** [comment]
> > Done ;)
> 
> You're still only messing with the 12-hour branch of the code though.
> 
> I push a commit to your branch (thanks for allowing that). How does that look to you?

Oh! sorry, I've changed the start time format instead of the end time format! :laughing:
Thank you so much. :+1:

**Comment by mortezaipo** [comment]
Just one question, when you'll release these changes? Because we need it in Emacs :+1:

**Comment by jcrowgey** [comment]
I'm actually wanting to do a release soon.  Not only this change but also the new prompt for calendar when doing `add` are both nice features to get out.

There are users who build from master, however, and many of them find errors and bugs.  Since I just merged a bunch of changes today, let's give this a little time (say, about a week), and then I can do a release to pypi.

You can of course pull from this repo if you need them sooner :)

**Pull request merged**
