### PR TITLE
Integrated RetryWithBackoff functionality

### PR DESCRIPTION
**Pull request by bdaigle**
After fixing "ist()" typo to "list()" in RetryWithBackoff branch, this functionality seems to work.

### CODE REVIEW

**Comment by tresni** [comment]
pretty bad when I forgot I wrote this code ;-)  I think the only reason I was holding off is that I was never able to hit the limits and as such had no idea if this code actually worked or not.  Granted it should be a "noop" if you aren't hitting the limits so....

**Comment by bdaigle** [comment]
I didn't thoroughly test the limits either, but I haven't had any issues since I've installed the branch (and I had a few "limit exceeded" errors before).

**Comment by tresni** [comment]
Not sure why this won't merge cleanly, but I'll see if I can get it pulled in :)  Was just waiting for some people to :+1: my changes, and thank you for catching the `ist -> list` issue.

**Comment by bdaigle** [comment]
Sounds good. Once you've pulled it in, I'll update the master branch of my fork and submit another PR for the new features I've added.

**Pull request closed without merging**
