### PR TITLE
config: New `config edit` subcommand to launch config.toml in an editor

### PR DESCRIPTION
**Pull request by dbarnett**

### CODE REVIEW

**Comment by glerner** [comment]
Copying the config.toml from the documentation makes errors

This simple config.toml generates errors: 

/home/george/.config/gcalcli/config.toml                                            
```
#:schema https://raw.githubusercontent.com/insanum/gcalcli/HEAD/data/config-schema.json
[calendars]
default-calendars = ["YOUREMAIL@gmail.com"]

```
Even an empty config.toml generates these errors: 

```gcalcli agenda
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/gcalcli/cli.py", line 187, in main
    opts_from_config = config.Config.from_toml(config_file)
  File "/usr/local/lib/python3.10/dist-packages/gcalcli/config.py", line 90, in from_toml
    config = tomllib.load(config_file)
  File "/home/george/.local/lib/python3.10/site-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/home/george/.local/lib/python3.10/site-packages/toml/decoder.py", line 186, in loads
    raise TypeError("Expecting something like a string")
TypeError: Expecting something like a string
```

A simple ```rm ~/.config/gcalcli/config.toml ``` makes it work again. 

```
gcalcli config edit
Launching ~/.config/gcalcli/config.toml in a text editor...
```
Make no changes, just save and exit, gcalcli Fails.

**Comment by dbarnett** [comment]
Indeed, I can repro using python3.10 and it looks like an easy fix: #801.

**Comment by glerner** [comment]
Linux Mint, and unknown others, still only have Python versions that fail. 
That makes your software look bad. 
How about make the needed Python version, required? Display a message when the Python version is lower than requirements.
How about trapping the error, and giving a message "This feature requires Python version ____"
Where are the instructions for upgrading from Phython 3.10 to version ____?

**Comment by dbarnett** [comment]
I'm not sure I follow your point but I already released the fix in 4.5.1. Are you just mentioning that Mint still doesn't have a package for 4.5.1, or trying to say that fix doesn't work? 

It's also easy to pipx install if your distro doesn't have up-to-date packages.

**Pull request merged**
