### PR TITLE
Add --nodeclined support to --tsv

### PR DESCRIPTION
**Pull request by lightheaded**
--tsv currently ignores the --nodeclined and still shows the events that you have declined in the list. This pull request adds the functionality to hide declined events from TSV list.

### CODE REVIEW

**Comment by lightheaded** [comment]
This would fix issue #306

**Comment by lightheaded** [comment]
This is still an issue. Any chance of fixing it?

**Comment by empierre** [comment]
yes would like it too

**Comment by dbarnett** [comment]
> This is still an issue. Any chance of fixing it?
Are you sure? It looks like it was fixed in 757cb0f back in 2018.

Maybe the changes weren't released to the version you're using?

**Comment by dbarnett** [comment]
Yeah, just tested it, `--nodeclined` definitely hides declined events for me with `--tsv` or without. Please reach out if you're still seeing issues.

**Pull request closed without merging**
