### PR TITLE
add environment.yml which actually makes it work

### PR DESCRIPTION
**Pull request by amitbeka**
Is this project still maintained? It has tons of useful functionality not found anywhere else :confused:

### CODE REVIEW

**Comment by tresni** [comment]
When I get around to it, yes.  Not sure what an envorionment.yml file is for though.

**Comment by amitbeka** [comment]
environment.yml is like requirements.txt, but for conda environments (a more general virtualenv, very popular in scientific python).

**Comment by jcrowgey** [comment]
For virtualenvironments, I think you can just enter and pip install.  Can you say what functionality this enables and for which OSes, distributions, etc?

**Comment by amitbeka** [comment]
I can't say it adds a crucial functionality, in conda you can pip install the requirements now if you want to. I did this mainly because the requirements file was un-maintained when I hacked with it so I shared back how to make it work :)

Closing the PR

**Pull request closed without merging**
