### PR TITLE
Fix import error

### PR DESCRIPTION
**Pull request by michaelmhoffman**
This fixed the problems with the import subcommand failing reported in #325.

### CODE REVIEW

**Comment by tresni** [comment]
I'm guessing you actually want this to go against the argparse_over_gflags branch that 4.0.0 is based on.

**Comment by michaelmhoffman** [comment]
@tresni I'm happy to start this over again. Is `argparse_over_gflags` the right branch for the main line of development? `master` seems to be the wrong place.

**Comment by tresni** [comment]
correct.  Looks like you have all the changes for argparse_over_gflags, which means it should just be opening the PR against the right base.  From what I can see I can't change it here...

**Comment by tresni** [comment]
Actually, looks like [I can do it]((https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/)!

**Pull request merged**
