### PR TITLE
[Proposal] add conference option `add --conference`  or `add --details conference`

### PR DESCRIPTION
**Pull request by sassy**
I want to make a  new event with Google Meet url.
Therefore, I would suggest adding the `conference` option to the `add` command.

I tried to add a `--detail conference` and `--conference`.

Please check it and consider this change.

### CODE REVIEW

**Comment by jcrowgey** [comment]
as of 4.3.0 we've already got `conference` in the --details output.  Afaik, the idea behind the conference stuff is that it should be possible to store other conference providers there beyond Google Meet.

@michaelmhoffman can you take a look at this PR?

**Comment by sassy** [comment]
@michaelmhoffman 
What do you think this PR?

**Comment by sassy** [comment]
@michaelmhoffman
What do you think this PR?

**Comment by michaelmhoffman** [comment]
I agree with @jcrowgey—I would suggest that the minimum for adding this kind of functionality is that the interface permits multiple conferencing providers. I don't think it would be absolutely necessary to implement more than one provider at first but you would want an interface that could expand to it if possible.

I also think the interface should allow specifying existing conference IDs and not just generating new ones—you might want generating a new interface to be a special case.

**Comment by sassy** [comment]
@michaelmhoffman 
Thank you for reviewing!
You make a good point. I rethink the interface for conference.
This PR is closed.

**Pull request closed without merging**
