### PR TITLE
Add 'updates' command.

### PR DESCRIPTION
**Pull request by flicken**
Use case: keeping a paper calendar in sync with an electronic Google calendar.

### CODE REVIEW

**Comment by jcrowgey** [comment]
Thanks for this!

I can see how this could be useful.  If you want to get this merged, I'll need a couple of things:

1) flake8 so that travis is happy
2) some rudimentary testing
3) documentation updates (since you're adding new functionality!)

I can probably help with some of this if you're interested in working on it.

Cheers!

**Comment by flicken** [comment]
Thanks for the response.  Fixed the flake8 issues and Travis is happy!

Anything in particular you'd like tested?

**Comment by flicken** [comment]
Write some simple tests and added some documentation.  Let me know if this is sufficient or if you'd like any changes.

**Comment by jcrowgey** [comment]
I was going to ask that in your test you actually update and event and assert something > 0.  But, alas, none of the other tests do any better.  So I think this is totally reasonable.  Thanks for this well-crafted PR!

**Pull request merged**
