### PR TITLE
Add a standard icon for notification

### PR DESCRIPTION
**Pull request by peterhoeg**
Pass a standard icon name to ```notify-send``` so the notification popup looks nicer.

### CODE REVIEW

**Comment by jcrowgey** [comment]
I'm on the fence about this.  It seems like a good idea for graphical notification managers, but I think that libnotify spams /var/log/messaes with silliness when you use this kind of thing with dunst (which doesn't support icons, to my knowledge).  In any case, can you rebase your changes on current master and then we can play with it?

**Comment by peterhoeg** [comment]
Rebased. 

I am not aware of the dunst log spam issue but isn't that a separate problem about a notification server not properly handling arguments passed to ```notify-send```? From gcalcli's point of view, you would want to present an attractive as possible interface.

Looks like dunst does support icons - from the dunst FAQ:

```
Icons are too big

Since the 1.2 version release, an option max_icon_size was introduced to scale down icons to a certain size. By default this option is set to 0 (it doesn’t scale down icons), to change this behaviour you need to set this option in the global section of the config file. For reference, check out the dunstrc config example file
```

**Comment by peterhoeg** [comment]
Assuming you're OK with moving ahead with this, we probably should use a standard icon name from https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html such as ```appointment-soon```.

**Comment by jcrowgey** [comment]
I think you're right on all accounts, including the idea that we should try to follow any in-place standards.  Do you want to push another commit with `appointment-soon` instead of `view-calendar-upcoming-events`?  I haven't looked at the standards but I assume that you have.  I'm fine to merge this as is if `view-calendar-upcoming-events` is the preferred name.

**Comment by peterhoeg** [comment]
I've changed the icon and squashed the commits.

**Comment by jcrowgey** [comment]
LGTM.  Thanks!

**Pull request merged**
