### PR TITLE
quick fix to re-enable edit of colour after refactor

### PR DESCRIPTION
**Pull request by hammerheadlemon**
See comment at #405.

### CODE REVIEW

**Comment by jcrowgey** [comment]
I'm happy to merge this, after you verify one thing for me ;)

In your commit to allow the validation, there were two places where the override_color_map was accessed:

https://github.com/insanum/gcalcli/blob/92fab4d39db319d91e5473d8df4cfef80b27e49c/gcalcli/gcalcli.py#L1318
 https://github.com/insanum/gcalcli/blob/92fab4d39db319d91e5473d8df4cfef80b27e49c/gcalcli/gcalcli.py#L954

One converted the number to a string, the other didn't.  Now, the nice thing is that if we really do need a `str`, we can do it in one place :).  But can you verify that we actually need a `str` here?  When I saw that it was done in two ways on the two lines, I assumed that the conversion to string was superfluous, and thusly I omitted it in the getter function.

**Comment by hammerheadlemon** [comment]
That's a really interesting point actually and there's a discrepancy in there I'm hunting down.  I'm tracking the `colorId` key that comes from the original JSON which is obviously a string once it gets into the Python code, but it does appear as an integer elsewhere.  I'm also of the view that `ansi_colors` should use ints as keys rather than strings and that your getter should return an integer. Preferable to use ints everywhere they make sense (indexes, keys, etc) and str/bytes where it makes (JSON). What do you think?

Give me a bit to look further into this and to make everything consistent, including the test fixture, which is also contributing to this inconsistency.

**Comment by hammerheadlemon** [comment]
I left a comment here yesterday but obviously didn't submit it for some reason - apologies for the delay.

In short, the getter function should return a `str`.

I got away with returning an `int` in the first example above because the `AddEvent` func builds an `event` that is eventually serialised by the library code before posting to the API. In the second example, we need a `str` because we're looking for a `str` key, which has been returned from the API.  So one way or another, we should be dealing with a `str` - either directly from the getter or by wrapping the the getter call.

**Comment by jcrowgey** [comment]
Thanks, @hammerheadlemon, for taking the time to research that for me.  :+1:

**Pull request merged**
