### PR TITLE
Don't require search_text when searching for events

### PR DESCRIPTION
**Pull request by booxter**
This allows to e.g. list all events scheduled for today with:

```
$ gcalcli ... search '' "today 00:00" "tomorrow 00:00"
```

### CODE REVIEW

**Comment by dbarnett** [comment]
Wdyt about printing a note to stderr for that case (and maybe making the code a little more explicit about empty search_text for readability)?

Seems like with multiple positional args it'd be easy to have a super confusing mixup otherwise. (For example if the text is supposed to come from an env variable but it's accidentally empty.)

**Comment by booxter** [comment]
I don't think this should be considered an error condition, and so `stderr` messages are probably not warranted. I am not sure what "making the code a little more explicit" means in this case, but perhaps we could add a special flag that would indicate that an empty value is desired. (basically, require something like: `gcalcli ... search '' "today 00:00" "tomorrow 00:00" --allow-empty-query`, otherwise, fail as done right now).

I don't necessarily think this should be done (an error like what you described should probably be caught before `gcalcli` is even called - by the calling party), but if you feel this is warranted, I am happy to update the patch accordingly. Let me know.

---

(Also, THANK YOU for the tool! In case you wonder about the use case, I am using it to [generate](https://github.com/booxter/nix/blob/d183da29a20ad4da1d58d73e1215b89239a4d1db/modules/home-manager/modules/meetings.nix#L42) a list of meetings for each work day, then use the list to create a separate note in my Obsidian vault per upcoming meeting. I was using `icalBuddy` before for the same, but it stopped working lately.)

**Comment by michaelmhoffman** [comment]
Some thoughts:

Comment looks like this error is designed for the case where start and end are also both unspecified so you don't get ALL events downloaded from the whole calendar, which could be pretty big.

This doesn't seem like a good use for `gcalcli search`. `gcalcli agenda` is what you should use when there's no search string. And its default start and end times add guardrails against getting the whole calendar. The implementation (`GoogleCalendarInterface._display_queried_events()`) is the same in either case.

All that said, `argparsers.get_search_parser()` gives an error if you don't specify anything, so you'll only get this if you really mean to, by submitting an empty

I'm -0 on this. It would be better to remove the `search` subcommand and add a search **option** for `agenda` instead.

**Comment by booxter** [comment]
I haven't realized that `agenda` can do what I need here. This PR is not needed, thanks for the pointer! :)

**Pull request closed without merging**
