### PR TITLE
Add a CONTRIBUTING.md with notes about community/reviews/guidelines/tests

### LINKED ISSUE #534: Add `CONTRIBUTING.md` with description of how to run tests
It's apparent that there are tests but not immediately apparent how to run them.

### PR DESCRIPTION
**Pull request by dbarnett**
Capturing a few up-to-date details after discussion in #688.

Fixes #534.

### CODE REVIEW

**Comment by dbarnett** [comment]
BTW, I was also wondering about policy questions like "should maintainers also wait to merge changes until getting review from a 2nd maintainer?", but I'm guessing y'all don't have strong opinions and I should just go with my gut on that... LMK concerns.

I also intend to make some tweaks to the automation/linters and how they run. Kept the notes about those pretty high-level for now.

And lastly, while I have your attention, does anyone have any pointers on how releasing/packaging is handled? Maybe that'd be @jcrowgey since he handled the last 4.3.0 release?

**Review by insanum — APPROVED** [review]

**Comment by dbarnett** [comment]
I'll go ahead and merge, but everyone please LMK if you can help answer any of my questions above or have other input to offer.

@mdengler too FYI

**Comment by jcrowgey** [comment]
... as far as process or any automation that I recall.

**Comment by jcrowgey** [comment]
It has been so long that I really don't recall.  I guess I would build everything and then push to pypi when it seemed like I had a reasonable set of changes that I wanted to get moving downstream.

I don't think I had anything formal as far as process.

**Pull request merged**
